"""add repo.architecture

Revision ID: 0c0231a8f34b
Revises: 858f1e39b0e6
Create Date: 2026-10-06 22:51:19.408320
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0c0231a8f34b'
down_revision: str | None = '858f1e39b0e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('architecture', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.drop_column('architecture')

    # ### end Alembic commands ###
