"""initial schema

Revision ID: 858f1e39b0e6
Revises: 
Create Date: 2026-10-06 22:19:24.331562
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '858f1e39b0e6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('github_login', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('github_access_token', sa.String(length=512), nullable=True),
    sa.Column('openrouter_api_key', sa.String(length=512), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_github_id'), ['github_id'], unique=True)

    op.create_table('repos',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('github_url', sa.String(length=1024), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'indexing', 'ready', 'failed', name='repostatus', native_enum=False, length=16), nullable=False),
    sa.Column('primary_language', sa.String(length=64), nullable=True),
    sa.Column('framework', sa.String(length=64), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('overview', sa.JSON(), nullable=True),
    sa.Column('graph', sa.JSON(), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('chroma_collection', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repos_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_repos_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repos_status'), ['status'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('repo_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_repo_id'), ['repo_id'], unique=False)

    op.create_table('index_jobs',
    sa.Column('repo_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'ready', 'failed', name='indexstatus', native_enum=False, length=16), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=2048), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('index_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_index_jobs_repo_id'), ['repo_id'], unique=False)

    op.create_table('roadmaps',
    sa.Column('repo_id', sa.String(length=36), nullable=False),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmaps_repo_id'), ['repo_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='chatrole', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmaps_repo_id'))

    op.drop_table('roadmaps')
    with op.batch_alter_table('index_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_index_jobs_repo_id'))

    op.drop_table('index_jobs')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_repo_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repos_status'))
        batch_op.drop_index(batch_op.f('ix_repos_owner_id'))
        batch_op.drop_index(batch_op.f('ix_repos_full_name'))

    op.drop_table('repos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_github_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
